const Expense = require('../models/Expense'); const RentPayment = require('../models/RentPayment'); const Maintenance = require('../models/MaintenanceRequest'); const Chore = require('../models/Chore'); const Settlement = require('../models/Settlement'); const Notification = require('../models/Notification'); const { getHouse, isAdmin, notify } = require('./helpers');
const modelFor = { maintenance: Maintenance, chores: Chore };
const populateExpenses = (query) => query.populate('paidBy splitBetween', 'name email');
const populateFeature = (query, feature) => feature === 'maintenance'
  ? query.populate('reportedBy assignedTo', 'name email')
  : query.populate('assignedTo', 'name email');
const populateSettlements = (query) => query.populate('from to', 'name email');
const memberId = (member) => (member._id || member).toString();
const splitMemberIds = (members) => [...new Set(members.map(memberId))];
const validateSplitMembers = (house, members) => {
  const houseMemberIds = new Set(house.members.map(memberId));
  const memberIds = splitMemberIds(members);
  if (!memberIds.length || memberIds.some((id) => !houseMemberIds.has(id))) throw new Error('Expenses can only be split between house members.');
  return memberIds;
};
const settlementsForExpense = (house, expense, payerId) => {
  const payer = payerId.toString();
  const participants = validateSplitMembers(house, expense.splitBetween);
  const share = expense.amount / participants.length;
  return participants.filter((participant) => participant !== payer).map((participant) => ({ house: house._id, from: participant, to: payer, amount: share, status: 'Pending', sourceExpense: expense._id }));
};
exports.listExpenses = async (req, res) => { const house = await getHouse(req.userId); if (!house) return res.json([]); res.json(await populateExpenses(Expense.find({ house: house._id }).sort('-date'))); };
exports.addExpense = async (req, res) => { try { const house = await getHouse(req.userId); if (!house) return res.status(400).json({ message: 'Join a house first.' }); const splitBetween = validateSplitMembers(house, req.body.splitBetween?.length ? req.body.splitBetween : house.members); const expense = await Expense.create({ ...req.body, house: house._id, paidBy: req.userId, splitBetween }); const settlements = settlementsForExpense(house, expense, req.userId); if (settlements.length) await Settlement.insertMany(settlements); await notify(house, `New ${expense.category} expense: ₹${expense.amount} added by you.`, 'Expense', req.userId); res.status(201).json(expense); } catch (error) { res.status(400).json({ message: error.message }); } };
exports.updateExpense = async (req, res) => { try { const house = await getHouse(req.userId); const expense = await Expense.findOne({ _id: req.params.id, house: house?._id }); if (!expense || expense.paidBy.toString() !== req.userId) return res.status(403).json({ message: 'Only the payer can update this expense.' }); const { paidBy, house: ignoredHouse, ...updates } = req.body; if (updates.splitBetween) updates.splitBetween = validateSplitMembers(house, updates.splitBetween); const shouldRegenerateSettlements = updates.amount !== undefined || updates.splitBetween !== undefined; Object.assign(expense, updates); await expense.save(); if (shouldRegenerateSettlements) { await Settlement.deleteMany({ sourceExpense: expense._id }); const settlements = settlementsForExpense(house, expense, expense.paidBy); if (settlements.length) await Settlement.insertMany(settlements); } await expense.populate('paidBy splitBetween', 'name email'); res.json(expense); } catch (error) { res.status(400).json({ message: error.message }); } };
exports.deleteExpense = async (req, res) => { const expense = await Expense.findById(req.params.id); if (!expense || expense.paidBy.toString() !== req.userId) return res.status(403).json({ message: 'Only the payer can delete this expense.' }); await Settlement.deleteMany({ sourceExpense: expense._id }); await expense.deleteOne(); res.json({ message: 'Expense removed.' }); };
exports.getRent = async (req, res) => { const house = await getHouse(req.userId); if (!house) return res.json({ house: null, payments: [] }); const month = new Date().toISOString().slice(0, 7); const amount = house.members.length ? house.monthlyRent / house.members.length : 0; const overdue = new Date().getDate() > house.rentDueDay; if (house.monthlyRent > 0) await Promise.all(house.members.map((user) => RentPayment.updateOne({ house: house._id, user, month }, { $setOnInsert: { amount, status: overdue ? 'Overdue' : 'Pending' } }, { upsert: true }))); const payments = await RentPayment.find({ house: house._id, month }).populate('user', 'name'); res.json({ house, payments, month }); };
exports.saveRent = async (req, res) => { const house = await getHouse(req.userId); if (!house || !isAdmin(house, req.userId)) return res.status(403).json({ message: 'Only the admin can configure rent.' }); house.monthlyRent = req.body.monthlyRent; house.rentDueDay = req.body.rentDueDay; await house.save(); res.json(house); };
exports.updateRent = async (req, res) => { const payment = await RentPayment.findById(req.params.id); const house = await getHouse(req.userId); if (!payment || !isAdmin(house, req.userId)) return res.status(403).json({ message: 'Only the admin can update payments.' }); Object.assign(payment, req.body); if (payment.status === 'Paid') payment.paidAt = new Date(); await payment.save(); res.json(payment); };
exports.listFeature = async (req, res) => { const house = await getHouse(req.userId); if (!house) return res.json([]); res.json(await populateFeature(modelFor[req.params.feature].find({ house: house._id }).sort('-createdAt'), req.params.feature)); };
exports.addFeature = async (req, res) => { try { const house = await getHouse(req.userId); if (!house) return res.status(400).json({ message: 'Join a house first.' }); const model = modelFor[req.params.feature]; const data = { ...req.body, house: house._id }; if (req.params.feature === 'maintenance') data.reportedBy = req.userId; if (req.params.feature === 'chores') { if (!data.assignedTo || !house.members.some((member) => memberId(member) === data.assignedTo)) return res.status(400).json({ message: 'Choose a member of this house to assign the chore.' }); } const item = await model.create(data); await notify(house, `New ${req.params.feature.slice(0, -1)}: ${item.title}`, req.params.feature, req.userId); res.status(201).json(item); } catch (error) { res.status(400).json({ message: error.message }); } };
exports.updateFeature = async (req, res) => { const house = await getHouse(req.userId); const item = await modelFor[req.params.feature].findById(req.params.id); if (!item || !isAdmin(house, req.userId)) return res.status(403).json({ message: 'Only the admin can update this item.' }); Object.assign(item, req.body); await item.save(); res.json(item); };
exports.settlements = async (req, res) => { const house = await getHouse(req.userId); if (!house) return res.json([]); res.json(await populateSettlements(Settlement.find({ house: house._id, $expr: { $ne: ['$from', '$to'] }, $or: [{ from: req.userId }, { to: req.userId }] }).sort('-createdAt'))); };
exports.paySettlement = async (req, res) => { const settlement = await Settlement.findById(req.params.id); if (!settlement || settlement.from.toString() !== req.userId) return res.status(403).json({ message: 'Only the person who owes can mark this paid.' }); settlement.status = 'Paid'; await settlement.save(); res.json(settlement); };
exports.notifications = async (req, res) => res.json(await Notification.find({ user: req.userId }).sort('-createdAt').limit(30));
exports.readNotification = async (req, res) => { const notification = await Notification.findOneAndUpdate({ _id: req.params.id, user: req.userId }, { read: true }, { new: true }); res.json(notification); };
exports.dashboard = async (req, res) => { const house = await getHouse(req.userId); if (!house) return res.json({ house: null }); const [expenses, settlements, maintenance, chores] = await Promise.all([Expense.find({ house: house._id }).sort('-date').limit(5).populate('paidBy', 'name'), Settlement.find({ house: house._id, status: 'Pending', $expr: { $ne: ['$from', '$to'] }, $or: [{ from: req.userId }, { to: req.userId }] }).populate('from to', 'name'), Maintenance.countDocuments({ house: house._id, status: { $ne: 'Resolved' } }), Chore.findOne({ house: house._id, assignedTo: req.userId, status: 'Pending' })]); const owes = settlements.filter((item) => item.from._id.toString() === req.userId).reduce((sum, item) => sum + item.amount, 0); const receives = settlements.filter((item) => item.to._id.toString() === req.userId).reduce((sum, item) => sum + item.amount, 0); res.json({ house, expenses, owes, receives, maintenance, chore: chores }); };
